spring:
  data:
    mongodb:
      uri: mongodb+srv://${DB_URL}?retryWrites=true&w=majority
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: 'https://msales.au.auth0.com/'

server:
  servlet:
    context-path: /api
  error:
    include-message: ALWAYS
  port: ${SERVER_PORT}

auth0:
  audience: 'http://public.api.msalesapp.com'
  grant-type: ""
  client-id: ""
  client-secret: ""
  api-audience: ""