spring:
  data:
    mongodb:
      uri: mongodb+srv://admin:IYtkNnoV8axchSVm@preercorecloudv3devclus.ac0wy6v.mongodb.net/competitor-activity
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: 'https://msales.au.auth0.com/'

server:
  servlet:
    context-path: /api
  error:
    include-message: ALWAYS
  port: 8081

auth0:
  audience: 'http://public.api.msalesapp.com'
  grant-type: ""
  client-id: ""
  client-secret: ""
  api-audience: ""